added train pod

diff --git a/workflows/build-initial.yaml b/workflows/build-initial.yaml
--- a/workflows/build-initial.yaml
+++ b/workflows/build-initial.yaml
@@ -20,6 +20,10 @@ spec:
           template: git-clone
       - - name: kaniko-build
           template: kaniko
+      - - name: clone-train-repo
+          template: train-git-clone
+      - - name: kaniko-train-build
+          template: kaniko-train
 
   - name: git-clone
     container:
@@ -60,3 +64,39 @@ spec:
         - name: workdir
           mountPath: /mnt/workspace
 
+  - name: train-git-clone
+    container:
+      image: alpine/git
+      command: [sh, -c]
+      args:
+        - |
+          MAX_RETRIES=5
+          i=1
+
+          while [ $i -le $MAX_RETRIES ]; do
+            echo "Attempt $i of $MAX_RETRIES: Cloning training repo..."
+            git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-train.git /mnt/workspace-train && break
+            echo "Git clone failed. Retrying in 5 seconds..."
+            i=$((i + 1))
+            sleep 5
+          done
+
+          if [ ! -d /mnt/workspace-train/.git ]; then
+            echo "Git clone failed after $MAX_RETRIES attempts."
+            exit 1
+          fi
+      volumeMounts:
+      - name: workdir
+        mountPath: /mnt/workspace-train
+
+  - name: kaniko-train
+    container:
+      image: gcr.io/kaniko-project/executor:latest
+      args:
+        - --dockerfile=/mnt/workspace-train/Dockerfile
+        - --context=/mnt/workspace-train
+        - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train:latest
+        - --insecure
+      volumeMounts:
+      - name: workdir
+        mountPath: /mnt/workspace-train
